jobs:
- job: CREATE_RELEASE
  pool:
    name: Hosted VS2017
    demands:
    - msbuild
    - visualstudio
    - vstest
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'specific'
      project: '$(DUSTPARTICLE_PROJECT)'
      definition: '$(DUSTPARTICLE_PIPELINE)'
      buildVersionToDownload: 'specific'
      pipelineId: '$(DUSTPARTICLE_BUILDID)'
      targetPath: '$(Pipeline.Workspace)'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Pipeline.Workspace)'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Pipeline.Workspace)/$(DUSTPARTICLE_BUILDID)-$(DUSTPARTICLE_RELEASETAG).zip'
      replaceExistingArchive: true
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'duytan8484'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(DUSTPARTICLE_SOURCEVERSION)'
      tagSource: 'userSpecifiedTag'
      tag: '$(DUSTPARTICLE_RELEASETAG)'
      assets: '$(Pipeline.Workspace)/$(DUSTPARTICLE_BUILDID)-$(DUSTPARTICLE_RELEASETAG).zip'
      addChangeLog: false
  - template: updateRevisionStatus.yml
    parameters:
      projectName: 'DustStream'
      status: $(Agent.JobStatus)