parameters:
- name: 'projectName'
  type: string
  default: false
- name: 'status'
  type: string
  default: false
- name: 'interval'
  type: number
  default: false
- name: 'timeout'
  type: number
  default: false

steps:
- script: 'npm install duststream-azure-pipelines'
- script: 'node updateJobStatus.js ${{parameters.projectName}} ${{parameters.status}} ${{parameters.interval}} ${{parameters.timeout}}'
  workingDirectory: node_modules\duststream-azure-pipelines
  env:
    MAPPED_API_KEY: $(WaterfallsApiKey)
  condition: always()
